name: CI
on:
  push:
    branches:
    - main
    paths:
    - src/**
    - ui/**
    - pom.xml
    - .github/workflows/*
  pull_request:
    branches:
    - main
    paths:
    - src/**
    - ui/**
    - pom.xml
    - .github/workflows/*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Install GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        cache: 'maven'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Unit Tests
      run: ./mvnw -V --no-transfer-progress clean test